# Generated by Django 5.2.4 on 2025-07-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ocenaEKG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlokAV_1stopnia', models.BooleanField(default=False)),
                ('RBBB', models.BooleanField(default=False)),
                ('LBBB', models.BooleanField(default=False)),
                ('Bradykardia', models.BooleanField(default=False)),
                ('Tachykardia', models.BooleanField(default=False)),
                ('Trzepotanie', models.BooleanField(default=False)),
                ('Migotanie', models.BooleanField(default=False)),
                ('ZalamekQ', models.BooleanField(default=False)),
                ('BlokAV_2stopnia1', models.BooleanField(default=False)),
                ('BlokAV_2stopnia2', models.BooleanField(default=False)),
                ('BlokAV_3stopnia', models.BooleanField(default=False)),
                ('CzyTrudne', models.BooleanField(default=False)),
            ],
        ),
    ]
