# Generated by Django 5.2.4 on 2025-07-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocenaekg',
            name='numer_zdjecia',
            field=models.IntegerField(default=0),
        ),
    ]
